// Merge translations-out/*.json into src/i18n/zh-CN.ts
// Usage: node scripts/merge-i18n.mjs
import { readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

const outDir = join(process.cwd(), 'translations-out');
const files = readdirSync(outDir).filter((f) => f.endsWith('.json'));
if (files.length === 0) {
  console.error('No translation JSON files found in translations-out/');
  process.exit(1);
}

const merged = new Map(); // key -> { value, sources: string[] }
const conflicts = [];

for (const file of files) {
  const data = JSON.parse(readFileSync(join(outDir, file), 'utf8'));
  for (const [key, value] of Object.entries(data)) {
    const existing = merged.get(key);
    if (existing) {
      if (existing.value !== value) {
        conflicts.push({ key, a: existing.value, b: value, sources: [existing.sources.join(','), file] });
        // Keep the first; conflicts are reported for manual resolution.
      } else {
        existing.sources.push(file);
      }
    } else {
      merged.set(key, { value, sources: [file] });
    }
  }
}

const sortedKeys = [...merged.keys()].sort((a, b) => a.localeCompare(b));
const lines = sortedKeys.map((key) => `  ${JSON.stringify(key)}: ${JSON.stringify(merged.get(key).value)},`);

const header = `/**
 * Chinese (Simplified) translations.
 *
 * Keys are the exact English source literals used in the UI, and values are
 * their Simplified Chinese translations. Interpolated placeholders such as
 * \`{count}\` must be preserved verbatim inside the value.
 *
 * Custom-node related UI intentionally stays in English and is NOT listed
 * here. Entries are kept sorted alphabetically by key.
 * Auto-generated by scripts/merge-i18n.mjs — do not edit by hand.
 */
export const zhCN: Record<string, string> = {
`;
const footer = `};
`;

writeFileSync(
  join(process.cwd(), 'src', 'i18n', 'zh-CN.ts'),
  header + lines.join('\n') + '\n' + footer,
  'utf8',
);

console.log(`Merged ${files.length} files -> ${merged.size} unique keys (${lines.length} lines).`);
if (conflicts.length > 0) {
  console.log(`\nCONFLICTS (${conflicts.length}) — resolved by keeping the first translation:`);
  for (const c of conflicts) {
    console.log(`  ${JSON.stringify(c.key)}`);
    console.log(`    A: ${JSON.stringify(c.a)} (from ${c.sources[0]})`);
    console.log(`    B: ${JSON.stringify(c.b)} (from ${c.sources[1]})`);
  }
}
